// src/pages/PolicyDetail.tsx
import { useEffect, useState, useCallback } from "react";
import { motion } from "framer-motion";
import { Navigate, Link, useNavigate, useSearchParams } from "react-router-dom";
import {
  ArrowLeft, Shield, Users, Calendar, CreditCard, FileText, Download, UserPlus,
  UserCog, UserMinus, ChevronRight, Loader2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useAuth } from "@/contexts/AuthContext";
import { useQuotationPersistence, type QuotationRecord } from "@/hooks/useQuotationPersistence";
import { useToast } from "@/hooks/use-toast";
import { downloadDocument } from "@/lib/download-document";
import { calculatePremium } from "@/lib/quotation-api";
import { ListPageSkeleton } from "@/components/skeletons/PageSkeletons";
import AddMemberEndorsement from "@/components/endorsement/AddMemberEndorsement";
import UpdateMemberEndorsement from "@/components/endorsement/UpdateMemberEndorsement";
import DeleteMemberEndorsement from "@/components/endorsement/DeleteMemberEndorsement";
import type { Member } from "@/types/quotation";

const fadeUp = { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 } };

const PolicyDetail = () => {
  const { user, isAuthenticated, isLoading } = useAuth();
  const navigate = useNavigate();
  const { toast } = useToast();
  const [searchParams] = useSearchParams();
  const policyId = searchParams.get("id");
  const { loadQuotation, saveState } = useQuotationPersistence(user?.id);
  const [policy, setPolicy] = useState<QuotationRecord | null>(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState("overview");
  const [endorsementView, setEndorsementView] = useState<"none" | "add" | "update" | "delete">("none");

  const load = useCallback(async () => {
    if (!policyId) return;
    setLoading(true);
    const data = await loadQuotation(policyId);
    if (data) {
      setPolicy({
        id: policyId,
        user_id: user?.id || "",
        status: data.status,
        current_step: data.currentStep,
        sponsor_data: data.sponsorData,
        members: data.members,
        kyc_data: data.kycData,
        total_premium: data.totalPremium,
        quotation_id: data.quotationCode || null,
        policy_number: data.policyNumber || null,
        created_at: "",
        updated_at: "",
      });
    }
    setLoading(false);
  }, [policyId, loadQuotation, user?.id]);

  useEffect(() => { if (user?.id && policyId) load(); }, [user?.id, policyId, load]);

  const handleDownload = () => {
    if (!policy) return;
    downloadDocument(policy, "policy");
    toast({ title: "Downloaded", description: "Policy document saved to your device" });
  };

  const handleMembersUpdated = async (updatedMembers: Member[], newPremium: number) => {
    if (!policy || !user?.id) return;
    await saveState(
      policy.id, policy.current_step, policy.sponsor_data, updatedMembers,
      policy.kyc_data, policy.status, newPremium, policy.quotation_id || undefined,
      policy.policy_number || undefined,
    );
    setPolicy({ ...policy, members: updatedMembers, total_premium: newPremium });
    setEndorsementView("none");
    setActiveTab("members");
    toast({ title: "Endorsement Applied", description: "Policy members have been updated successfully." });
  };

  if (isLoading || loading) {
    return (
      <div className="min-h-screen bg-section-alt">
        <header className="sticky top-0 z-50 border-b border-border bg-card/95 backdrop-blur-md">
          <div className="container mx-auto flex h-16 items-center px-4 lg:px-8 gap-4">
            <Link to="/policies"><Button variant="ghost" size="icon"><ArrowLeft className="h-5 w-5" /></Button></Link>
            <h1 className="text-lg font-heading font-bold text-foreground">Policy Details</h1>
          </div>
        </header>
        <main className="container mx-auto px-4 py-8 lg:px-8 max-w-5xl"><ListPageSkeleton count={3} /></main>
      </div>
    );
  }

  if (!isAuthenticated || !user) return <Navigate to="/login" replace />;
  if (!policy) return <Navigate to="/policies" replace />;

  const sponsor = policy.sponsor_data as any;
  const members = (policy.members as Member[]) || [];
  const premiums = calculatePremium(members);

  return (
    <div className="min-h-screen bg-section-alt">
      <header className="sticky top-0 z-50 border-b border-border bg-card/95 backdrop-blur-md">
        <div className="container mx-auto flex h-16 items-center justify-between px-4 lg:px-8">
          <div className="flex items-center gap-4">
            <Link to="/policies"><Button variant="ghost" size="icon"><ArrowLeft className="h-5 w-5" /></Button></Link>
            <div>
              <h1 className="text-lg font-heading font-bold text-foreground">
                {policy.policy_number || policy.quotation_id || "Policy"}
              </h1>
              <p className="text-xs text-muted-foreground">{sponsor?.sponsorName || "—"}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" className="gap-1.5" onClick={handleDownload}>
              <Download className="h-3.5 w-3.5" /> Download
            </Button>
            <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">
              {user.avatar}
            </div>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8 lg:px-8 max-w-5xl space-y-6">
        {endorsementView !== "none" ? (
          <motion.div {...fadeUp} transition={{ duration: 0.3 }}>
            {endorsementView === "add" && (
              <AddMemberEndorsement
                existingMembers={members}
                sponsorNumber={sponsor?.sponsorNumber || ""}
                onComplete={handleMembersUpdated}
                onCancel={() => setEndorsementView("none")}
              />
            )}
            {endorsementView === "update" && (
              <UpdateMemberEndorsement
                members={members}
                onComplete={handleMembersUpdated}
                onCancel={() => setEndorsementView("none")}
              />
            )}
            {endorsementView === "delete" && (
              <DeleteMemberEndorsement
                members={members}
                sponsorNumber={sponsor?.sponsorNumber || ""}
                onComplete={handleMembersUpdated}
                onCancel={() => setEndorsementView("none")}
              />
            )}
          </motion.div>
        ) : (
          <>
            {/* Policy Summary Cards */}
            <motion.div {...fadeUp} transition={{ duration: 0.3 }} className="grid grid-cols-2 md:grid-cols-4 gap-4">
              {[
                { label: "Total Premium", value: `SAR ${(policy.total_premium || 0).toLocaleString()}`, icon: CreditCard, tone: "bg-primary/10 text-primary" },
                { label: "Members", value: String(members.length), icon: Users, tone: "bg-secondary text-secondary-foreground" },
                { label: "Status", value: policy.status === "paid" ? "Active" : "Completed", icon: Shield, tone: "bg-primary/10 text-primary" },
                { label: "Effective Date", value: sponsor?.policyEffectiveDate ? new Date(sponsor.policyEffectiveDate).toLocaleDateString() : "—", icon: Calendar, tone: "bg-accent text-accent-foreground" },
              ].map((s) => (
                <Card key={s.label} className="border-border">
                  <CardContent className="p-4 flex items-center gap-3">
                    <div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl ${s.tone}`}>
                      <s.icon className="h-5 w-5" />
                    </div>
                    <div className="min-w-0">
                      <p className="text-xs text-muted-foreground">{s.label}</p>
                      <p className="text-sm font-heading font-bold text-foreground truncate">{s.value}</p>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </motion.div>

            {/* Endorsement Actions */}
            <motion.div {...fadeUp} transition={{ duration: 0.3, delay: 0.05 }}>
              <Card className="border-border">
                <CardHeader className="pb-3">
                  <CardTitle className="font-heading text-lg">Endorsements</CardTitle>
                  <p className="text-sm text-muted-foreground">Modify your policy members through endorsements.</p>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                    <Button
                      variant="outline"
                      className="h-auto py-4 flex flex-col items-center gap-2 hover:border-primary/30 hover:bg-primary/5 transition-all"
                      onClick={() => setEndorsementView("add")}
                    >
                      <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-primary/10 text-primary">
                        <UserPlus className="h-5 w-5" />
                      </div>
                      <div className="text-center">
                        <p className="text-sm font-semibold text-foreground">Add Member</p>
                        <p className="text-xs text-muted-foreground">Add new members with health declaration</p>
                      </div>
                    </Button>
                    <Button
                      variant="outline"
                      className="h-auto py-4 flex flex-col items-center gap-2 hover:border-primary/30 hover:bg-primary/5 transition-all"
                      onClick={() => setEndorsementView("update")}
                    >
                      <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-secondary text-secondary-foreground">
                        <UserCog className="h-5 w-5" />
                      </div>
                      <div className="text-center">
                        <p className="text-sm font-semibold text-foreground">Update Member</p>
                        <p className="text-xs text-muted-foreground">Edit basic personal details</p>
                      </div>
                    </Button>
                    <Button
                      variant="outline"
                      className="h-auto py-4 flex flex-col items-center gap-2 hover:border-destructive/30 hover:bg-destructive/5 transition-all"
                      onClick={() => setEndorsementView("delete")}
                    >
                      <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-destructive/10 text-destructive">
                        <UserMinus className="h-5 w-5" />
                      </div>
                      <div className="text-center">
                        <p className="text-sm font-semibold text-foreground">Delete Member</p>
                        <p className="text-xs text-muted-foreground">Remove members with refund calculation</p>
                      </div>
                    </Button>
                  </div>
                </CardContent>
              </Card>
            </motion.div>

            {/* Tabs: Overview & Members */}
            <motion.div {...fadeUp} transition={{ duration: 0.3, delay: 0.1 }}>
              <Tabs value={activeTab} onValueChange={setActiveTab}>
                <TabsList className="mb-4">
                  <TabsTrigger value="overview">Overview</TabsTrigger>
                  <TabsTrigger value="members">Members ({members.length})</TabsTrigger>
                </TabsList>

                <TabsContent value="overview">
                  <Card className="border-border">
                    <CardContent className="p-6 space-y-4">
                      <div className="grid grid-cols-2 md:grid-cols-3 gap-y-4 gap-x-6 text-sm">
                        <div><p className="text-muted-foreground">Policy Number</p><p className="font-semibold text-foreground">{policy.policy_number || "—"}</p></div>
                        <div><p className="text-muted-foreground">Quotation ID</p><p className="font-semibold text-foreground">{policy.quotation_id || "—"}</p></div>
                        <div><p className="text-muted-foreground">Sponsor Name</p><p className="font-semibold text-foreground">{sponsor?.sponsorName || "—"}</p></div>
                        <div><p className="text-muted-foreground">Sponsor Number</p><p className="font-semibold text-foreground">{sponsor?.sponsorNumber || "—"}</p></div>
                        <div><p className="text-muted-foreground">Effective Date</p><p className="font-semibold text-foreground">{sponsor?.policyEffectiveDate ? new Date(sponsor.policyEffectiveDate).toLocaleDateString() : "—"}</p></div>
                        <div><p className="text-muted-foreground">Total Premium</p><p className="font-semibold text-primary">SAR {(policy.total_premium || 0).toLocaleString()}</p></div>
                      </div>
                    </CardContent>
                  </Card>
                </TabsContent>

                <TabsContent value="members">
                  <Card className="border-border">
                    <CardContent className="p-0">
                      <div className="overflow-auto max-h-[500px]">
                        <table className="w-full text-sm">
                          <thead className="sticky top-0 bg-card z-10">
                            <tr className="border-b border-border text-left">
                              <th className="py-3 px-4 font-semibold text-muted-foreground">#</th>
                              <th className="py-3 px-4 font-semibold text-muted-foreground">Name</th>
                              <th className="py-3 px-4 font-semibold text-muted-foreground">Type</th>
                              <th className="py-3 px-4 font-semibold text-muted-foreground hidden sm:table-cell">ID Number</th>
                              <th className="py-3 px-4 font-semibold text-muted-foreground">Class</th>
                              <th className="py-3 px-4 font-semibold text-muted-foreground hidden md:table-cell">Gender</th>
                              <th className="py-3 px-4 font-semibold text-muted-foreground text-right">Premium</th>
                            </tr>
                          </thead>
                          <tbody>
                            {members.map((m, i) => (
                              <tr key={m.id} className="border-b border-border last:border-0 hover:bg-muted/50 transition-colors">
                                <td className="py-3 px-4 text-muted-foreground">{i + 1}</td>
                                <td className="py-3 px-4 font-medium text-foreground">{m.memberName}</td>
                                <td className="py-3 px-4"><Badge variant="outline" className={m.memberType === "Employee" ? "border-primary/30 text-primary" : ""}>{m.memberType}</Badge></td>
                                <td className="py-3 px-4 text-muted-foreground hidden sm:table-cell">{m.identityNumber}</td>
                                <td className="py-3 px-4"><Badge variant="secondary">{m.classSelection}</Badge></td>
                                <td className="py-3 px-4 text-muted-foreground hidden md:table-cell">{m.gender}</td>
                                <td className="py-3 px-4 text-right font-semibold">SAR {(premiums[i] || 0).toLocaleString()}</td>
                              </tr>
                            ))}
                          </tbody>
                          <tfoot>
                            <tr className="border-t-2 border-border bg-muted/30">
                              <td colSpan={6} className="py-3 px-4 font-heading font-bold text-foreground">Total</td>
                              <td className="py-3 px-4 text-right font-heading font-bold text-primary">SAR {premiums.reduce((a, b) => a + b, 0).toLocaleString()}</td>
                            </tr>
                          </tfoot>
                        </table>
                      </div>
                    </CardContent>
                  </Card>
                </TabsContent>
              </Tabs>
            </motion.div>
          </>
        )}
      </main>
    </div>
  );
};

export default PolicyDetail;

// public/angular-project/src/app/features/policy/pages/policy-detail/policy-detail.component.ts
import { Component, OnInit, signal, inject, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterLink, Router } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatTabsModule } from '@angular/material/tabs';
import { MatChipsModule } from '@angular/material/chips';
import { MatTableModule } from '@angular/material/table';
import { MatDividerModule } from '@angular/material/divider';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';

import { AuthService } from '../../../../core/services/auth.service';
import { QuotationService } from '../../../../core/services/quotation.service';
import { EndorsementService } from '../../../../core/services/endorsement.service';
import { ToastService } from '../../../../core/services/toast.service';
import { SarCurrencyPipe } from '../../../../shared/pipes/format-currency.pipe';
import { QuotationRecord, Member, calculatePremium } from '../../../../core/models/quotation.model';
import { EndorsementHistoryItem } from '../../../../core/models/endorsement.model';

@Component({
  selector: 'app-policy-detail',
  standalone: true,
  imports: [
    CommonModule, RouterLink,
    MatCardModule, MatButtonModule, MatTabsModule, MatChipsModule,
    MatTableModule, MatDividerModule, MatProgressSpinnerModule,
    SarCurrencyPipe,
  ],
  template: `
    <div class="min-h-screen bg-section-alt">
      <!-- Header -->
      <header class="sticky top-0 z-50 border-b border-border bg-card/95 backdrop-blur-md">
        <div class="container mx-auto flex h-16 items-center justify-between px-4 lg:px-8">
          <div class="flex items-center gap-4">
            <a routerLink="/policies"><button mat-icon-button>←</button></a>
            <div>
              <h1 class="text-lg font-heading font-bold text-foreground">
                {{ policy()?.policyNumber || policy()?.quotationId || 'Policy' }}
              </h1>
              <p class="text-xs text-muted-foreground">{{ sponsorName() }}</p>
            </div>
          </div>
          <div class="flex items-center gap-2">
            <button mat-stroked-button (click)="handleDownload()">📥 Download</button>
          </div>
        </div>
      </header>

      @if (loading()) {
        <main class="container mx-auto px-4 py-8 lg:px-8 max-w-5xl text-center">
          <mat-spinner diameter="40" class="mx-auto"></mat-spinner>
        </main>
      } @else if (policy()) {
        <main class="container mx-auto px-4 py-8 lg:px-8 max-w-5xl space-y-6">

          @if (endorsementView() !== 'none') {
            <!-- Endorsement Views -->
            <div>
              @switch (endorsementView()) {
                @case ('add') {
                  <!-- <app-add-member-endorsement ...> -->
                  <mat-card>
                    <mat-card-content class="p-8 text-center">
                      <p>Add Member Endorsement Component</p>
                      <button mat-button (click)="endorsementView.set('none')">Cancel</button>
                    </mat-card-content>
                  </mat-card>
                }
                @case ('update') {
                  <mat-card>
                    <mat-card-content class="p-8 text-center">
                      <p>Update Member Endorsement Component</p>
                      <button mat-button (click)="endorsementView.set('none')">Cancel</button>
                    </mat-card-content>
                  </mat-card>
                }
                @case ('delete') {
                  <mat-card>
                    <mat-card-content class="p-8 text-center">
                      <p>Delete Member Endorsement Component</p>
                      <button mat-button (click)="endorsementView.set('none')">Cancel</button>
                    </mat-card-content>
                  </mat-card>
                }
              }
            </div>
          } @else {
            <!-- Summary Cards -->
            <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
              @for (s of summaryCards(); track s.label) {
                <mat-card>
                  <mat-card-content class="p-4 flex items-center gap-3">
                    <div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl {{ s.tone }}">
                      {{ s.icon }}
                    </div>
                    <div class="min-w-0">
                      <p class="text-xs text-muted-foreground">{{ s.label }}</p>
                      <p class="text-sm font-heading font-bold text-foreground truncate">{{ s.value }}</p>
                    </div>
                  </mat-card-content>
                </mat-card>
              }
            </div>

            <!-- Endorsement Actions -->
            <mat-card>
              <mat-card-header>
                <mat-card-title class="font-heading text-lg">Endorsements</mat-card-title>
                <mat-card-subtitle>Modify your policy members through endorsements.</mat-card-subtitle>
              </mat-card-header>
              <mat-card-content>
                <div class="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-4">
                  <button mat-stroked-button class="h-auto py-4" (click)="endorsementView.set('add')">
                    <div class="text-center">
                      <p class="text-sm font-semibold">👤+ Add Member</p>
                      <p class="text-xs text-muted-foreground mt-1">Add new members with health declaration</p>
                    </div>
                  </button>
                  <button mat-stroked-button class="h-auto py-4" (click)="endorsementView.set('update')">
                    <div class="text-center">
                      <p class="text-sm font-semibold">✏️ Update Member</p>
                      <p class="text-xs text-muted-foreground mt-1">Edit basic personal details</p>
                    </div>
                  </button>
                  <button mat-stroked-button class="h-auto py-4" (click)="endorsementView.set('delete')">
                    <div class="text-center">
                      <p class="text-sm font-semibold">🗑️ Delete Member</p>
                      <p class="text-xs text-muted-foreground mt-1">Remove members with refund</p>
                    </div>
                  </button>
                </div>
              </mat-card-content>
            </mat-card>

            <!-- Tabs: Overview / Members / Endorsements -->
            <mat-tab-group [(selectedIndex)]="selectedTab">
              <mat-tab label="Overview">
                <mat-card class="mt-4">
                  <mat-card-content class="p-6">
                    <div class="grid grid-cols-2 md:grid-cols-3 gap-y-4 gap-x-6 text-sm">
                      <div><p class="text-muted-foreground">Policy Number</p><p class="font-semibold">{{ policy()?.policyNumber || '—' }}</p></div>
                      <div><p class="text-muted-foreground">Quotation ID</p><p class="font-semibold">{{ policy()?.quotationId || '—' }}</p></div>
                      <div><p class="text-muted-foreground">Sponsor Name</p><p class="font-semibold">{{ sponsorName() }}</p></div>
                      <div><p class="text-muted-foreground">Total Premium</p><p class="font-semibold text-primary">{{ policy()?.totalPremium | sarCurrency }}</p></div>
                    </div>
                  </mat-card-content>
                </mat-card>
              </mat-tab>

              <mat-tab [label]="'Members (' + members().length + ')'">
                <mat-card class="mt-4">
                  <mat-card-content class="p-0">
                    <table mat-table [dataSource]="members()" class="w-full">
                      <ng-container matColumnDef="index">
                        <th mat-header-cell *matHeaderCellDef>#</th>
                        <td mat-cell *matCellDef="let m; let i = index">{{ i + 1 }}</td>
                      </ng-container>
                      <ng-container matColumnDef="name">
                        <th mat-header-cell *matHeaderCellDef>Name</th>
                        <td mat-cell *matCellDef="let m">{{ m.memberName }}</td>
                      </ng-container>
                      <ng-container matColumnDef="type">
                        <th mat-header-cell *matHeaderCellDef>Type</th>
                        <td mat-cell *matCellDef="let m"><mat-chip>{{ m.memberType }}</mat-chip></td>
                      </ng-container>
                      <ng-container matColumnDef="class">
                        <th mat-header-cell *matHeaderCellDef>Class</th>
                        <td mat-cell *matCellDef="let m"><mat-chip>{{ m.classSelection }}</mat-chip></td>
                      </ng-container>
                      <ng-container matColumnDef="premium">
                        <th mat-header-cell *matHeaderCellDef>Premium</th>
                        <td mat-cell *matCellDef="let m; let i = index">{{ premiums()[i] | sarCurrency }}</td>
                      </ng-container>
                      <tr mat-header-row *matHeaderRowDef="memberColumns"></tr>
                      <tr mat-row *matRowDef="let row; columns: memberColumns"></tr>
                    </table>
                  </mat-card-content>
                </mat-card>
              </mat-tab>

              <mat-tab [label]="'Endorsements (' + endorsementHistory().length + ')'">
                <mat-card class="mt-4">
                  <mat-card-content class="p-4">
                    @if (endorsementHistory().length === 0) {
                      <p class="text-center text-muted-foreground py-8">No endorsement history yet.</p>
                    } @else {
                      <div class="space-y-3">
                        @for (item of endorsementHistory(); track item.id) {
                          <div class="flex items-start gap-3 rounded-xl border border-border p-4">
                            <div class="flex-1">
                              <div class="flex items-center gap-2 mb-1">
                                <p class="text-sm font-semibold text-foreground">{{ item.description }}</p>
                                <mat-chip class="text-xs">{{ item.status }}</mat-chip>
                              </div>
                              <p class="text-xs text-muted-foreground">{{ item.date | date:'medium' }}</p>
                              @if (item.details) {
                                <p class="text-xs text-muted-foreground mt-1">{{ item.details }}</p>
                              }
                            </div>
                            @if (item.premiumImpact != null && item.premiumImpact !== 0) {
                              <p class="text-sm font-bold"
                                 [class.text-primary]="item.premiumImpact > 0"
                                 [class.text-destructive]="item.premiumImpact < 0">
                                {{ item.premiumImpact > 0 ? '+' : '' }}{{ item.premiumImpact | sarCurrency }}
                              </p>
                            }
                          </div>
                        }
                      </div>
                    }
                  </mat-card-content>
                </mat-card>
              </mat-tab>
            </mat-tab-group>
          }
        </main>
      }
    </div>
  `,
})
export class PolicyDetailComponent implements OnInit {
  private auth = inject(AuthService);
  private quotationService = inject(QuotationService);
  private endorsementService = inject(EndorsementService);
  private toast = inject(ToastService);
  private route = inject(ActivatedRoute);

  policy = signal<QuotationRecord | null>(null);
  loading = signal(true);
  endorsementView = signal<'none' | 'add' | 'update' | 'delete'>('none');
  endorsementHistory = signal<EndorsementHistoryItem[]>([]);
  selectedTab = 0;

  memberColumns = ['index', 'name', 'type', 'class', 'premium'];

  members = computed(() => this.policy()?.members ?? []);
  premiums = computed(() => calculatePremium(this.members()));
  sponsorName = computed(() => {
    const sponsor = this.policy()?.sponsorData;
    return sponsor?.sponsorName || sponsor?.sponsorNumber || '—';
  });

  summaryCards = computed(() => {
    const p = this.policy();
    if (!p) return [];
    return [
      { label: 'Total Premium', value: `SAR ${(p.totalPremium || 0).toLocaleString()}`, icon: '💳', tone: 'bg-primary/10 text-primary' },
      { label: 'Members', value: String(this.members().length), icon: '👥', tone: 'bg-secondary text-secondary-foreground' },
      { label: 'Status', value: p.status === 'paid' ? 'Active' : 'Completed', icon: '🛡️', tone: 'bg-primary/10 text-primary' },
      { label: 'Effective Date', value: p.sponsorData?.policyEffectiveDate ? new Date(p.sponsorData.policyEffectiveDate).toLocaleDateString() : '—', icon: '📅', tone: 'bg-accent text-accent-foreground' },
    ];
  });

  async ngOnInit(): Promise<void> {
    const policyId = this.route.snapshot.queryParamMap.get('id');
    if (!policyId) return;

    this.loading.set(true);
    const data = await this.quotationService.loadQuotation(policyId);
    if (data) {
      this.policy.set(data);

      // Load endorsement history
      const history = await this.endorsementService.getHistory(policyId);
      this.endorsementHistory.set(history.items);
    }
    this.loading.set(false);
  }

  handleDownload(): void {
    const p = this.policy();
    if (!p) return;
    this.quotationService.downloadDocument(p.id, 'policy');
    this.toast.success('Downloaded', 'Policy document saved');
  }
}
