// src/pages/Dashboard.tsx
import { useEffect, useState, useCallback } from "react";
import { motion } from "framer-motion";
import { Navigate, Link, useNavigate } from "react-router-dom";
import {
  Shield,
  FileText,
  CreditCard,
  TrendingUp,
  AlertCircle,
  CheckCircle,
  Clock,
  ChevronRight,
  LogOut,
  User,
  Bell,
  Calendar,
  Activity,
  Heart,
  Loader2,
  Plus,
  ArrowRight,
  Trash2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Separator } from "@/components/ui/separator";
import { useAuth } from "@/contexts/AuthContext";
import { useQuotationPersistence, type QuotationRecord } from "@/hooks/useQuotationPersistence";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

const initialNotifications = [
  { id: 1, title: "Claim Approved", desc: "Your claim CLM-1023 for ₹45,000 has been approved.", time: "2 hours ago", read: false, icon: CheckCircle, tone: "text-primary" },
  { id: 2, title: "Payment Reminder", desc: "Health Shield Plus premium of ₹18,500 is due on 15 Mar.", time: "1 day ago", read: false, icon: CreditCard, tone: "text-accent-foreground" },
  { id: 3, title: "Claim Under Review", desc: "Claim CLM-1024 for Motor Protect is being reviewed.", time: "3 days ago", read: true, icon: Clock, tone: "text-muted-foreground" },
  { id: 4, title: "Policy Renewed", desc: "Life Secure 360 has been renewed successfully.", time: "1 week ago", read: true, icon: CheckCircle, tone: "text-primary" },
];

const policies = [
  {
    id: "POL-2024-001",
    name: "Health Shield Plus",
    type: "Health Insurance",
    premium: "₹18,500/yr",
    coverage: "₹10,00,000",
    status: "Active",
    renewal: "15 Mar 2026",
    icon: Heart,
    tone: "bg-primary/10 text-primary",
  },
  {
    id: "POL-2024-002",
    name: "Motor Protect",
    type: "Vehicle Insurance",
    premium: "₹8,200/yr",
    coverage: "₹5,00,000",
    status: "Active",
    renewal: "22 Jul 2025",
    icon: Shield,
    tone: "bg-secondary text-secondary-foreground",
  },
  {
    id: "POL-2024-003",
    name: "Life Secure 360",
    type: "Life Insurance",
    premium: "₹24,000/yr",
    coverage: "₹50,00,000",
    status: "Active",
    renewal: "01 Jan 2027",
    icon: Activity,
    tone: "bg-accent text-accent-foreground",
  },
];

const claims = [
  { id: "CLM-1023", policy: "Health Shield Plus", amount: "₹45,000", date: "12 Jan 2025", status: "Approved" },
  { id: "CLM-1024", policy: "Motor Protect", amount: "₹12,500", date: "28 Feb 2025", status: "In Review" },
  { id: "CLM-1025", policy: "Health Shield Plus", amount: "₹8,200", date: "01 Mar 2025", status: "Pending" },
];

const payments = [
  { policy: "Health Shield Plus", amount: "₹18,500", date: "15 Mar 2025", status: "Upcoming" },
  { policy: "Life Secure 360", amount: "₹24,000", date: "01 Jan 2026", status: "Upcoming" },
  { policy: "Motor Protect", amount: "₹8,200", date: "22 Jul 2025", status: "Upcoming" },
];

const statusColors: Record<string, string> = {
  Active: "bg-primary/10 text-primary border-primary/20",
  Approved: "bg-primary/10 text-primary border-primary/20",
  "In Review": "bg-secondary text-secondary-foreground border-border",
  Pending: "bg-accent text-accent-foreground border-border",
  Upcoming: "bg-muted text-muted-foreground border-border",
};

const statusIcons: Record<string, typeof CheckCircle> = {
  Approved: CheckCircle,
  "In Review": Clock,
  Pending: AlertCircle,
};

const fadeUp = {
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
};

const Dashboard = () => {
  const { user, isAuthenticated, isLoading, logout } = useAuth();
  const navigate = useNavigate();
  const { toast } = useToast();
  const { listQuotations } = useQuotationPersistence(user?.id);
  const [quotations, setQuotations] = useState<QuotationRecord[]>([]);
  const [notifications, setNotifications] = useState(initialNotifications);
  const unreadCount = notifications.filter((n) => !n.read).length;

  const markAllRead = () => {
    setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
  };

  const markOneRead = (id: number) => {
    setNotifications((prev) => prev.map((n) => n.id === id ? { ...n, read: true } : n));
  };

  const loadQuotations = useCallback(() => {
    if (user?.id) listQuotations().then(setQuotations);
  }, [user?.id, listQuotations]);

  useEffect(() => { loadQuotations(); }, [loadQuotations]);

  const handleDeleteQuotation = async (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    const { error } = await supabase.from("quotations").delete().eq("id", id);
    if (error) {
      toast({ title: "Error", description: "Failed to delete quotation", variant: "destructive" });
    } else {
      toast({ title: "Deleted", description: "Quotation removed successfully" });
      loadQuotations();
    }
  };

  if (isLoading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-section-alt">
        <div className="inline-flex items-center gap-3 rounded-full border border-border bg-card px-5 py-3 text-sm text-muted-foreground shadow-sm">
          <Loader2 className="h-4 w-4 animate-spin text-primary" />
          Loading your insurance workspace...
        </div>
      </div>
    );
  }

  if (!isAuthenticated || !user) return <Navigate to="/login" replace />;

  const handleLogout = async () => {
    await logout();
    navigate("/");
  };

  return (
    <div className="min-h-screen bg-section-alt">
      <header className="sticky top-0 z-50 border-b border-border bg-card/95 backdrop-blur-md">
        <div className="container mx-auto flex h-16 items-center justify-between px-4 lg:px-8">
          <Link to="/" className="flex items-center gap-2">
            <div className="flex items-center gap-1">
              <div className="h-3 w-3 rounded-full bg-primary" />
              <div className="h-3 w-3 rounded-full bg-primary" />
            </div>
            <span className="text-xl font-heading font-bold tracking-tight text-foreground">FataFat</span>
          </Link>
          <div className="flex items-center gap-3">
            <Popover>
              <PopoverTrigger asChild>
                <Button variant="ghost" size="icon" className="relative">
                  <Bell className="h-5 w-5" />
                  {unreadCount > 0 && (
                    <span className="absolute right-1.5 top-1.5 h-2 w-2 rounded-full bg-primary" />
                  )}
                </Button>
              </PopoverTrigger>
              <PopoverContent align="end" className="w-80 p-0">
                <div className="flex items-center justify-between px-4 py-3">
                  <p className="text-sm font-heading font-semibold text-foreground">Notifications</p>
                  {unreadCount > 0 && (
                    <Badge variant="outline" className="text-xs">{unreadCount} new</Badge>
                  )}
                </div>
                <Separator />
                <div className="max-h-80 overflow-y-auto">
                  {notifications.map((n) => (
                    <div
                      key={n.id}
                      className={`flex items-start gap-3 px-4 py-3 transition-colors hover:bg-muted cursor-pointer ${!n.read ? "bg-primary/5" : ""}`}
                      onClick={() => markOneRead(n.id)}
                    >
                      <div className={`mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-card ${n.tone}`}>
                        <n.icon className="h-4 w-4" />
                      </div>
                      <div className="min-w-0 flex-1">
                        <p className="text-sm font-medium text-foreground">{n.title}</p>
                        <p className="text-xs text-muted-foreground line-clamp-2">{n.desc}</p>
                        <p className="mt-1 text-xs text-muted-foreground/70">{n.time}</p>
                      </div>
                      {!n.read && <span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-primary" />}
                    </div>
                  ))}
                </div>
                <Separator />
                <div className="px-4 py-2">
                  <Button
                    variant="ghost"
                    size="sm"
                    className="w-full text-xs text-primary"
                    onClick={markAllRead}
                    disabled={unreadCount === 0}
                  >
                    {unreadCount === 0 ? "All caught up!" : "Mark all as read"}
                  </Button>
                </div>
              </PopoverContent>
            </Popover>
            <Link to="/profile">
              <Button variant="ghost" size="sm" className="gap-2">
                <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">
                  {user.avatar}
                </div>
                <span className="hidden text-sm font-medium sm:inline">{user.name}</span>
              </Button>
            </Link>
            <Button variant="ghost" size="icon" onClick={handleLogout} title="Logout">
              <LogOut className="h-5 w-5" />
            </Button>
          </div>
        </div>
      </header>

      <main className="container mx-auto space-y-8 px-4 py-8 lg:px-8">
        <motion.div {...fadeUp} transition={{ duration: 0.4 }} className="grid gap-5 lg:grid-cols-[1.2fr_0.8fr]">
          <div>
            <p className="text-sm font-medium uppercase tracking-[0.24em] text-primary">Policy command center</p>
            <h1 className="mt-3 text-2xl font-heading font-bold text-foreground md:text-3xl">
              Welcome back, {user.name.split(" ")[0]} 👋
            </h1>
            <p className="mt-2 text-muted-foreground">Track claims, billing, and member details from one secure dashboard.</p>
          </div>
          <Card className="border-border bg-card shadow-sm">
            <CardContent className="flex h-full flex-col justify-between gap-4 p-5">
              <div>
                <p className="text-sm text-muted-foreground">Membership</p>
                <p className="mt-1 text-xl font-heading font-semibold text-foreground">{user.membershipTier}</p>
              </div>
              <div className="flex flex-wrap gap-2 text-sm text-muted-foreground">
                <Badge variant="outline" className="border-primary/20 bg-primary/10 text-primary">
                  {user.policyCount} active policies
                </Badge>
                <Badge variant="outline">Member since {user.memberSince}</Badge>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        <motion.div {...fadeUp} transition={{ duration: 0.4, delay: 0.1 }} className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {[
            { label: "Active Policies", value: String(user.policyCount), icon: Shield, tone: "bg-primary/10 text-primary" },
            { label: "Total Coverage", value: "₹65 Lakh", icon: TrendingUp, tone: "bg-secondary text-secondary-foreground" },
            { label: "Annual Premium", value: "₹50,700", icon: CreditCard, tone: "bg-accent text-accent-foreground" },
            { label: "Open Claims", value: "2", icon: FileText, tone: "bg-muted text-muted-foreground" },
          ].map((stat) => (
            <Card key={stat.label} className="border-border transition-shadow hover:shadow-md">
              <CardContent className="flex items-center gap-4 p-5">
                <div className={`flex h-12 w-12 items-center justify-center rounded-2xl ${stat.tone}`}>
                  <stat.icon className="h-5 w-5" />
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">{stat.label}</p>
                  <p className="text-2xl font-heading font-bold text-foreground">{stat.value}</p>
                </div>
              </CardContent>
            </Card>
          ))}
        </motion.div>

        <motion.div {...fadeUp} transition={{ duration: 0.4, delay: 0.2 }}>
          <div className="mb-4 flex items-center justify-between">
            <h2 className="text-lg font-heading font-bold text-foreground">Your Policies</h2>
            <Button variant="ghost" size="sm" className="gap-1 text-primary" onClick={() => navigate("/policies")}>
              View All <ChevronRight className="h-4 w-4" />
            </Button>
          </div>
          <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
            {policies.map((policy) => (
              <Card key={policy.id} className="group cursor-pointer border-border transition-all hover:shadow-lg">
                <CardContent className="p-6">
                  <div className="mb-4 flex items-start justify-between">
                    <div className={`flex h-11 w-11 items-center justify-center rounded-2xl ${policy.tone}`}>
                      <policy.icon className="h-5 w-5" />
                    </div>
                    <Badge variant="outline" className={statusColors[policy.status]}>
                      {policy.status}
                    </Badge>
                  </div>
                  <h3 className="font-heading font-bold text-foreground">{policy.name}</h3>
                  <p className="mb-4 text-sm text-muted-foreground">{policy.type}</p>
                  <div className="space-y-2 text-sm">
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Coverage</span>
                      <span className="font-semibold text-foreground">{policy.coverage}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Premium</span>
                      <span className="font-semibold text-foreground">{policy.premium}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Renewal</span>
                      <span className="font-semibold text-foreground">{policy.renewal}</span>
                    </div>
                  </div>
                  <div className="mt-4 border-t border-border pt-4">
                    <p className="text-xs text-muted-foreground">Policy ID: {policy.id}</p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </motion.div>

        <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
          <motion.div {...fadeUp} transition={{ duration: 0.4, delay: 0.3 }}>
            <Card className="border-border">
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <CardTitle className="text-lg font-heading">Recent Claims</CardTitle>
                  <Button variant="ghost" size="sm" className="gap-1 text-primary">
                    View All <ChevronRight className="h-4 w-4" />
                  </Button>
                </div>
              </CardHeader>
              <CardContent className="space-y-3">
                {claims.map((claim) => {
                  const Icon = statusIcons[claim.status] || Clock;
                  return (
                    <div key={claim.id} className="flex items-center justify-between rounded-2xl bg-section-alt p-3 transition-colors hover:bg-muted">
                      <div className="flex items-center gap-3">
                        <div className="flex h-10 w-10 items-center justify-center rounded-full bg-card text-primary">
                          <Icon className="h-5 w-5" />
                        </div>
                        <div>
                          <p className="text-sm font-medium text-foreground">{claim.id}</p>
                          <p className="text-xs text-muted-foreground">
                            {claim.policy} · {claim.date}
                          </p>
                        </div>
                      </div>
                      <div className="text-right">
                        <p className="text-sm font-semibold text-foreground">{claim.amount}</p>
                        <Badge variant="outline" className={`text-xs ${statusColors[claim.status]}`}>
                          {claim.status}
                        </Badge>
                      </div>
                    </div>
                  );
                })}
              </CardContent>
            </Card>
          </motion.div>

          <motion.div {...fadeUp} transition={{ duration: 0.4, delay: 0.35 }}>
            <Card className="border-border">
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <CardTitle className="text-lg font-heading">Upcoming Payments</CardTitle>
                  <Button variant="ghost" size="sm" className="gap-1 text-primary">
                    Pay Now <CreditCard className="h-4 w-4" />
                  </Button>
                </div>
              </CardHeader>
              <CardContent className="space-y-3">
                {payments.map((payment) => (
                  <div key={`${payment.policy}-${payment.date}`} className="flex items-center justify-between rounded-2xl bg-section-alt p-3 transition-colors hover:bg-muted">
                    <div className="flex items-center gap-3">
                      <Calendar className="h-5 w-5 text-primary" />
                      <div>
                        <p className="text-sm font-medium text-foreground">{payment.policy}</p>
                        <p className="text-xs text-muted-foreground">Due: {payment.date}</p>
                      </div>
                    </div>
                    <div className="text-right">
                      <p className="text-sm font-semibold text-foreground">{payment.amount}</p>
                      <Badge variant="outline" className={`text-xs ${statusColors[payment.status]}`}>
                        {payment.status}
                      </Badge>
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>
          </motion.div>
        </div>

        {/* Saved Quotations */}
        {quotations.length > 0 && (
          <motion.div {...fadeUp} transition={{ duration: 0.4, delay: 0.38 }}>
            <div className="mb-4 flex items-center justify-between">
              <h2 className="text-lg font-heading font-bold text-foreground">Your Quotations</h2>
              <div className="flex gap-2">
                <Button variant="ghost" size="sm" className="gap-1 text-primary" onClick={() => navigate("/quotations")}>
                  View All <ChevronRight className="h-4 w-4" />
                </Button>
                <Button variant="ghost" size="sm" className="gap-1 text-primary" onClick={() => navigate("/quotation")}>
                  <Plus className="h-4 w-4" /> New
                </Button>
              </div>
            </div>
            <div className="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-3">
              {quotations.slice(0, 6).map((q) => {
                const stepLabels = ["Sponsor", "Members", "Health", "Quotation", "KYC", "Payment"];
                const sponsor = q.sponsor_data as any;
                const memberCount = Array.isArray(q.members) ? q.members.length : 0;
                const statusColor = q.status === "completed" ? "bg-primary/10 text-primary border-primary/20"
                  : q.status === "paid" ? "bg-primary/10 text-primary border-primary/20"
                  : "bg-muted text-muted-foreground border-border";
                return (
                  <Card
                    key={q.id}
                    className="group cursor-pointer border-border transition-all hover:border-primary/30 hover:shadow-md"
                    onClick={() => navigate(`/quotation?id=${q.id}`)}
                  >
                    <CardContent className="p-5">
                      <div className="flex items-start justify-between mb-3">
                        <div>
                          <p className="text-sm font-semibold text-foreground">
                            {sponsor?.sponsorName || sponsor?.sponsorNumber || "Draft Quotation"}
                          </p>
                          <p className="text-xs text-muted-foreground mt-0.5">
                            {q.quotation_id || `Step: ${stepLabels[q.current_step] || "Sponsor"}`}
                          </p>
                        </div>
                        <Badge variant="outline" className={`text-xs ${statusColor}`}>
                          {q.status === "draft" ? "In Progress" : q.status}
                        </Badge>
                      </div>
                      <div className="flex items-center justify-between text-xs text-muted-foreground">
                        <span>{memberCount} member{memberCount !== 1 ? "s" : ""}</span>
                        <div className="flex items-center gap-2">
                          {q.status === "draft" && (
                            <button
                              onClick={(e) => handleDeleteQuotation(e, q.id)}
                              className="flex items-center gap-1 text-destructive hover:text-destructive/80 transition-colors"
                              title="Delete draft"
                            >
                              <Trash2 className="h-3 w-3" />
                            </button>
                          )}
                          <span className="flex items-center gap-1">
                            {q.status === "draft" ? "Resume" : "View"} <ArrowRight className="h-3 w-3" />
                          </span>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          </motion.div>
        )}

        <motion.div {...fadeUp} transition={{ duration: 0.4, delay: 0.4 }}>
          <h2 className="mb-4 text-lg font-heading font-bold text-foreground">Quick Actions</h2>
          <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
            {[
              { label: "File a Claim", icon: FileText, desc: "Submit new claim", href: "" },
              { label: "Buy New Policy", icon: Shield, desc: "Start quotation", href: "/quotation" },
              { label: "Make Payment", icon: CreditCard, desc: "Pay premium", href: "" },
              { label: "Get Support", icon: User, desc: "Talk to advisor", href: "" },
            ].map((action) => (
              <Card
                key={action.label}
                className="group cursor-pointer border-border transition-all hover:border-primary/30 hover:shadow-md"
                onClick={() => action.href && navigate(action.href)}
              >
                <CardContent className="p-5 text-center">
                  <div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary transition-colors group-hover:bg-primary/15">
                    <action.icon className="h-6 w-6" />
                  </div>
                  <p className="text-sm font-semibold text-foreground">{action.label}</p>
                  <p className="mt-1 text-xs text-muted-foreground">{action.desc}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </motion.div>
      </main>
    </div>
  );
};

export default Dashboard;

// public/angular-project/src/app/features/dashboard/pages/dashboard/dashboard.component.ts
import { Component, OnInit, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, Router } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatMenuModule } from '@angular/material/menu';
import { MatBadgeModule } from '@angular/material/badge';
import { MatChipsModule } from '@angular/material/chips';
import { MatDividerModule } from '@angular/material/divider';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { AuthService } from '../../../../core/services/auth.service';
import { QuotationService } from '../../../../core/services/quotation.service';
import { ToastService } from '../../../../core/services/toast.service';
import { QuotationRecord } from '../../../../core/models/quotation.model';
import { SarCurrencyPipe } from '../../../../shared/pipes/format-currency.pipe';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [
    CommonModule, RouterLink,
    MatCardModule, MatButtonModule, MatMenuModule, MatBadgeModule,
    MatChipsModule, MatDividerModule, MatProgressSpinnerModule,
    SarCurrencyPipe,
  ],
  template: `
    <div class="min-h-screen bg-section-alt">
      <!-- Header -->
      <header class="sticky top-0 z-50 border-b border-border bg-card/95 backdrop-blur-md">
        <div class="container mx-auto flex h-16 items-center justify-between px-4 lg:px-8">
          <a routerLink="/" class="flex items-center gap-2">
            <div class="flex items-center gap-1">
              <div class="h-3 w-3 rounded-full bg-primary"></div>
              <div class="h-3 w-3 rounded-full bg-primary"></div>
            </div>
            <span class="text-xl font-heading font-bold tracking-tight text-foreground">FataFat</span>
          </a>
          <div class="flex items-center gap-3">
            <!-- Notification Bell -->
            <button mat-icon-button [matMenuTriggerFor]="notifMenu">
              🔔
              @if (unreadCount() > 0) {
                <span class="absolute right-1.5 top-1.5 h-2 w-2 rounded-full bg-primary"></span>
              }
            </button>
            <mat-menu #notifMenu="matMenu" class="w-80">
              <div class="px-4 py-3 flex items-center justify-between">
                <p class="text-sm font-heading font-semibold">Notifications</p>
                @if (unreadCount() > 0) {
                  <mat-chip class="text-xs">{{ unreadCount() }} new</mat-chip>
                }
              </div>
              <mat-divider></mat-divider>
              @for (n of notifications(); track n.id) {
                <button mat-menu-item (click)="markOneRead(n.id)">
                  <div class="flex flex-col py-1">
                    <span class="text-sm font-medium">{{ n.title }}</span>
                    <span class="text-xs text-muted-foreground">{{ n.desc }}</span>
                    <span class="text-xs text-muted-foreground/70 mt-1">{{ n.time }}</span>
                  </div>
                </button>
              }
              <mat-divider></mat-divider>
              <button mat-menu-item (click)="markAllRead()" [disabled]="unreadCount() === 0">
                {{ unreadCount() === 0 ? 'All caught up!' : 'Mark all as read' }}
              </button>
            </mat-menu>

            <!-- Profile -->
            <a routerLink="/profile">
              <button mat-button class="gap-2">
                <div class="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">
                  {{ auth.user()?.avatar }}
                </div>
                <span class="hidden sm:inline text-sm font-medium">{{ auth.user()?.name }}</span>
              </button>
            </a>

            <!-- Logout -->
            <button mat-icon-button (click)="handleLogout()" title="Logout">🚪</button>
          </div>
        </div>
      </header>

      <!-- Main -->
      <main class="container mx-auto space-y-8 px-4 py-8 lg:px-8">
        <!-- Welcome -->
        <div class="grid gap-5 lg:grid-cols-[1.2fr_0.8fr]">
          <div>
            <p class="text-sm font-medium uppercase tracking-[0.24em] text-primary">Policy command center</p>
            <h1 class="mt-3 text-2xl font-heading font-bold text-foreground md:text-3xl">
              Welcome back, {{ auth.user()?.name?.split(' ')?.[0] }} 👋
            </h1>
            <p class="mt-2 text-muted-foreground">Track claims, billing, and member details from one secure dashboard.</p>
          </div>
          <mat-card>
            <mat-card-content class="flex h-full flex-col justify-between gap-4 p-5">
              <div>
                <p class="text-sm text-muted-foreground">Membership</p>
                <p class="mt-1 text-xl font-heading font-semibold">{{ auth.user()?.membershipTier }}</p>
              </div>
              <div class="flex flex-wrap gap-2 text-sm text-muted-foreground">
                <mat-chip class="bg-primary/10 text-primary">{{ auth.user()?.policyCount }} active policies</mat-chip>
                <mat-chip>Member since {{ auth.user()?.memberSince }}</mat-chip>
              </div>
            </mat-card-content>
          </mat-card>
        </div>

        <!-- Stats -->
        <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
          @for (stat of dashboardStats; track stat.label) {
            <mat-card class="hover:shadow-md transition-shadow">
              <mat-card-content class="flex items-center gap-4 p-5">
                <div class="flex h-12 w-12 items-center justify-center rounded-2xl {{ stat.tone }}">
                  {{ stat.icon }}
                </div>
                <div>
                  <p class="text-sm text-muted-foreground">{{ stat.label }}</p>
                  <p class="text-2xl font-heading font-bold text-foreground">{{ stat.value }}</p>
                </div>
              </mat-card-content>
            </mat-card>
          }
        </div>

        <!-- Quotations -->
        @if (quotations().length > 0) {
          <div>
            <div class="mb-4 flex items-center justify-between">
              <h2 class="text-lg font-heading font-bold">Your Quotations</h2>
              <a routerLink="/quotations"><button mat-button color="primary">View All →</button></a>
            </div>
            <div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
              @for (q of quotations().slice(0, 6); track q.id) {
                <mat-card class="cursor-pointer hover:shadow-lg transition-all"
                          (click)="navigateToQuotation(q)">
                  <mat-card-content class="p-5">
                    <div class="flex items-center justify-between mb-3">
                      <p class="font-heading font-bold text-foreground text-sm">
                        {{ q.quotationId || q.id.slice(0, 8) }}
                      </p>
                      <mat-chip class="text-xs">{{ q.status }}</mat-chip>
                    </div>
                    <p class="text-sm text-muted-foreground">
                      {{ q.members.length }} members · {{ q.totalPremium | sarCurrency }}
                    </p>
                    <div class="mt-3 flex justify-end">
                      <button mat-icon-button color="warn" (click)="deleteQuotation($event, q.id)">🗑️</button>
                    </div>
                  </mat-card-content>
                </mat-card>
              }
            </div>
          </div>
        }

        <!-- New Quotation Button -->
        <div class="text-center">
          <a routerLink="/quotation">
            <button mat-flat-button color="primary" class="gap-2">
              + Start New Quotation
            </button>
          </a>
        </div>
      </main>
    </div>
  `,
})
export class DashboardComponent implements OnInit {
  auth = inject(AuthService);
  private quotationService = inject(QuotationService);
  private toast = inject(ToastService);
  private router = inject(Router);

  quotations = signal<QuotationRecord[]>([]);
  notifications = signal([
    { id: 1, title: 'Claim Approved', desc: 'Your claim CLM-1023 for ₹45,000 has been approved.', time: '2 hours ago', read: false },
    { id: 2, title: 'Payment Reminder', desc: 'Health Shield Plus premium of ₹18,500 is due on 15 Mar.', time: '1 day ago', read: false },
    { id: 3, title: 'Claim Under Review', desc: 'Claim CLM-1024 for Motor Protect is being reviewed.', time: '3 days ago', read: true },
  ]);

  unreadCount = signal(2);

  dashboardStats = [
    { label: 'Active Policies', value: '3', icon: '🛡️', tone: 'bg-primary/10 text-primary' },
    { label: 'Total Coverage', value: '₹65 Lakh', icon: '📈', tone: 'bg-secondary text-secondary-foreground' },
    { label: 'Annual Premium', value: '₹50,700', icon: '💳', tone: 'bg-accent text-accent-foreground' },
    { label: 'Open Claims', value: '2', icon: '📄', tone: 'bg-muted text-muted-foreground' },
  ];

  async ngOnInit(): Promise<void> {
    const user = this.auth.user();
    if (user) {
      const quotations = await this.quotationService.listQuotations(user.id);
      this.quotations.set(quotations);
    }
  }

  markAllRead(): void {
    this.notifications.update(n => n.map(item => ({ ...item, read: true })));
    this.unreadCount.set(0);
  }

  markOneRead(id: number): void {
    this.notifications.update(n => n.map(item => item.id === id ? { ...item, read: true } : item));
    this.unreadCount.set(this.notifications().filter(n => !n.read).length);
  }

  navigateToQuotation(q: QuotationRecord): void {
    if (q.status === 'paid' || q.policyNumber) {
      this.router.navigate(['/policy'], { queryParams: { id: q.id } });
    } else {
      this.router.navigate(['/quotation'], { queryParams: { id: q.id } });
    }
  }

  async deleteQuotation(event: Event, id: string): Promise<void> {
    event.stopPropagation();
    const success = await this.quotationService.deleteQuotation(id);
    if (success) {
      this.quotations.update(list => list.filter(q => q.id !== id));
      this.toast.success('Deleted', 'Quotation removed');
    } else {
      this.toast.error('Error', 'Failed to delete');
    }
  }

  async handleLogout(): Promise<void> {
    await this.auth.logout();
  }
}
