// public/angular-project/src/app/features/quotation/components/members-step/members-step.component.ts
import { Component, EventEmitter, Input, Output, computed, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Member, MemberType, ClassSelection, Gender, MaritalStatus } from '../../../../core/models/quotation.model';

const CLASS_OPTIONS: ClassSelection[] = ['VIP', 'A', 'B', 'C', 'LM'];

@Component({
  selector: 'app-members-step',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="space-y-6 pb-20 sm:pb-0">
      <!-- Members Card -->
      <div class="bg-card border border-border rounded-2xl overflow-hidden">
        <div class="p-6 pb-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
          <h3 class="text-xl font-bold">Members</h3>
          <div class="flex flex-wrap gap-2">
            <button (click)="downloadTemplate()" class="flex items-center gap-1.5 px-3 py-1.5 text-sm hover:bg-muted rounded-lg transition-colors">
              <span class="material-icons text-sm">download</span> <span class="hidden xs:inline">Template</span>
            </button>
            <label for="excel-upload" class="flex items-center gap-1.5 px-3 py-1.5 text-sm border border-border rounded-lg cursor-pointer hover:bg-muted transition-colors">
              <span class="material-icons text-sm">upload</span> Upload
            </label>
            <input id="excel-upload" type="file" accept=".xlsx,.xls" class="hidden" (change)="onExcelUpload($event)" />
            <button (click)="openAdd()" class="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors">
              <span class="material-icons text-sm">add</span> Add
            </button>
          </div>
        </div>
        <div class="px-6 pb-6">
          @if (uploadErrors.length > 0) {
            <div class="mb-4 rounded-lg border border-red-300 bg-red-50 p-3 text-sm text-red-600 space-y-1">
              <p class="font-semibold">Upload Errors:</p>
              @for (err of uploadErrors; track err) {
                <p>• {{ err }}</p>
              }
            </div>
          }

          @if (members.length === 0) {
            <div class="text-center py-12 text-muted-foreground">
              <p class="text-sm">No members added yet. Click "Add" or upload an Excel file.</p>
              <p class="text-xs mt-2">Excel columns: MemberType, MemberName, IdentityNumber, DateOfBirth, Gender, MaritalStatus, Class, SponsorNumber</p>
            </div>
          } @else {
            <div class="overflow-auto max-h-[420px]">
              <table class="w-full text-sm">
                <thead class="sticky top-0 bg-card z-10">
                  <tr class="border-b border-border text-left">
                    <th class="py-2.5 px-3 font-semibold text-muted-foreground">Name</th>
                    <th class="py-2.5 px-3 font-semibold text-muted-foreground">Type</th>
                    <th class="py-2.5 px-3 font-semibold text-muted-foreground hidden sm:table-cell">Sponsor #</th>
                    <th class="py-2.5 px-3 font-semibold text-muted-foreground">Class</th>
                    <th class="py-2.5 px-3 font-semibold text-muted-foreground hidden md:table-cell">Marital</th>
                    <th class="py-2.5 px-3 font-semibold text-muted-foreground text-right">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  @for (m of members; track m.id) {
                    <tr class="border-b border-border last:border-0 hover:bg-muted/50 transition-colors">
                      <td class="py-2.5 px-3 font-medium text-foreground">{{ m.memberName }}</td>
                      <td class="py-2.5 px-3">
                        <span class="text-xs px-2 py-0.5 rounded-full border" [class.border-primary/30]="m.memberType === 'Employee'" [class.text-primary]="m.memberType === 'Employee'">
                          {{ m.memberType }}
                        </span>
                      </td>
                      <td class="py-2.5 px-3 text-muted-foreground hidden sm:table-cell">{{ m.sponsorNumber }}</td>
                      <td class="py-2.5 px-3"><span class="text-xs px-2 py-0.5 rounded-full bg-secondary">{{ m.classSelection }}</span></td>
                      <td class="py-2.5 px-3 text-muted-foreground hidden md:table-cell">{{ m.maritalStatus }}</td>
                      <td class="py-2.5 px-3 text-right">
                        <button (click)="openEdit(m)" class="p-1.5 rounded hover:bg-muted"><span class="material-icons text-sm">edit</span></button>
                        <button (click)="deleteMember(m.id)" class="p-1.5 rounded hover:bg-red-50 text-red-500"><span class="material-icons text-sm">delete</span></button>
                      </td>
                    </tr>
                  }
                </tbody>
              </table>
            </div>
          }
          <p class="text-xs text-muted-foreground mt-3">{{ members.length }} member(s) added</p>
        </div>
      </div>

      <!-- Navigation -->
      <div class="hidden sm:flex justify-between">
        <button (click)="back.emit()" class="px-6 py-2.5 border border-border rounded-lg hover:bg-muted transition-colors">Back</button>
        <button (click)="goNext()" [disabled]="members.length === 0"
          class="px-6 py-2.5 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors disabled:opacity-50">Continue</button>
      </div>

      <!-- Mobile Bottom Bar -->
      <div class="fixed bottom-0 left-0 right-0 z-40 border-t border-border bg-card/95 backdrop-blur-md p-3 flex gap-3 sm:hidden">
        <button (click)="back.emit()" class="flex-1 px-4 py-2.5 border border-border rounded-lg">Back</button>
        <button (click)="goNext()" [disabled]="members.length === 0"
          class="flex-1 px-4 py-2.5 bg-primary text-primary-foreground rounded-lg disabled:opacity-50">Continue</button>
      </div>

      <!-- Add/Edit Dialog Overlay -->
      @if (dialogOpen) {
        <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50" (click)="dialogOpen = false">
          <div class="bg-card rounded-2xl border border-border shadow-xl w-full max-w-md mx-4 p-6" (click)="$event.stopPropagation()">
            <h3 class="text-lg font-bold mb-4">{{ editingId ? 'Edit' : 'Add' }} Member</h3>
            <div class="space-y-4">
              <!-- Member Type -->
              <div class="space-y-1.5">
                <label class="text-sm font-medium">Member Type</label>
                <select [(ngModel)]="form.memberType" (ngModelChange)="form.employeeId = undefined"
                  class="w-full px-3 py-2 border border-border rounded-lg bg-background text-sm">
                  <option value="Employee">Employee</option>
                  <option value="Dependent">Dependent</option>
                </select>
              </div>

              @if (form.memberType === 'Dependent') {
                <div class="space-y-1.5">
                  <label class="text-sm font-medium">Select Employee *</label>
                  <select [(ngModel)]="form.employeeId"
                    class="w-full px-3 py-2 border border-border rounded-lg bg-background text-sm">
                    <option value="">Choose employee</option>
                    @for (emp of employees(); track emp.id) {
                      <option [value]="emp.id">{{ emp.memberName }} ({{ emp.identityNumber }})</option>
                    }
                  </select>
                  @if (employees().length === 0) {
                    <p class="text-xs text-red-500">Add an employee first.</p>
                  }
                </div>
              }

              <div class="space-y-1.5">
                <label class="text-sm font-medium">Member Name *</label>
                <input [(ngModel)]="form.memberName" class="w-full px-3 py-2 border border-border rounded-lg bg-background text-sm" />
              </div>

              <div class="space-y-1.5">
                <label class="text-sm font-medium">Identity Number *</label>
                <input [(ngModel)]="form.identityNumber" class="w-full px-3 py-2 border border-border rounded-lg bg-background text-sm" />
              </div>

              <div class="grid grid-cols-2 gap-3">
                <div class="space-y-1.5">
                  <label class="text-sm font-medium">Date of Birth *</label>
                  <input type="date" [(ngModel)]="form.dateOfBirth" class="w-full px-3 py-2 border border-border rounded-lg bg-background text-sm" />
                </div>
                <div class="space-y-1.5">
                  <label class="text-sm font-medium">Gender</label>
                  <select [(ngModel)]="form.gender" class="w-full px-3 py-2 border border-border rounded-lg bg-background text-sm">
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                  </select>
                </div>
              </div>

              <div class="grid grid-cols-2 gap-3">
                <div class="space-y-1.5">
                  <label class="text-sm font-medium">Marital Status</label>
                  <select [(ngModel)]="form.maritalStatus" class="w-full px-3 py-2 border border-border rounded-lg bg-background text-sm">
                    <option value="Single">Single</option>
                    <option value="Married">Married</option>
                  </select>
                </div>
                <div class="space-y-1.5">
                  <label class="text-sm font-medium">Class *</label>
                  <select [(ngModel)]="form.classSelection" class="w-full px-3 py-2 border border-border rounded-lg bg-background text-sm">
                    @for (c of classOptions; track c) {
                      <option [value]="c">{{ c }}</option>
                    }
                  </select>
                </div>
              </div>

              @if (formError) {
                <p class="text-sm text-red-500">{{ formError }}</p>
              }
            </div>

            <div class="flex justify-end gap-3 mt-6">
              <button (click)="dialogOpen = false" class="px-4 py-2 border border-border rounded-lg hover:bg-muted text-sm">Cancel</button>
              <button (click)="saveMember()" class="px-4 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 text-sm">
                {{ editingId ? 'Update' : 'Add' }}
              </button>
            </div>
          </div>
        </div>
      }
    </div>
  `,
})
export class MembersStepComponent {
  @Input() members: Member[] = [];
  @Input() sponsorNumber = '';
  @Output() membersChange = new EventEmitter<Member[]>();
  @Output() next = new EventEmitter<void>();
  @Output() back = new EventEmitter<void>();

  classOptions = CLASS_OPTIONS;
  dialogOpen = false;
  editingId: string | null = null;
  formError = '';
  uploadErrors: string[] = [];

  form: Omit<Member, 'id'> = this.emptyMember();

  employees = computed(() => {
    const membersSignal = signal(this.members);
    return membersSignal().filter(m => m.memberType === 'Employee');
  });

  private emptyMember(): Omit<Member, 'id'> {
    return {
      memberType: 'Employee', memberName: '', identityNumber: '',
      dateOfBirth: '', gender: 'Male', maritalStatus: 'Single',
      classSelection: 'B', sponsorNumber: this.sponsorNumber,
    };
  }

  openAdd(): void {
    this.form = this.emptyMember();
    this.editingId = null;
    this.formError = '';
    this.dialogOpen = true;
  }

  openEdit(member: Member): void {
    const { id, ...rest } = member;
    this.form = { ...rest };
    this.editingId = id;
    this.formError = '';
    this.dialogOpen = true;
  }

  deleteMember(id: string): void {
    const member = this.members.find(m => m.id === id);
    if (member?.memberType === 'Employee') {
      this.membersChange.emit(this.members.filter(m => m.id !== id && m.employeeId !== id));
    } else {
      this.membersChange.emit(this.members.filter(m => m.id !== id));
    }
  }

  saveMember(): void {
    const err = this.validate();
    if (err) { this.formError = err; return; }

    const finalSponsor = this.form.memberType === 'Employee'
      ? this.sponsorNumber
      : this.members.find(m => m.id === this.form.employeeId)?.identityNumber || this.sponsorNumber;

    if (this.editingId) {
      this.membersChange.emit(
        this.members.map(m => m.id === this.editingId
          ? { ...this.form, id: this.editingId!, sponsorNumber: finalSponsor }
          : m
        )
      );
    } else {
      this.membersChange.emit([
        ...this.members,
        { ...this.form, id: crypto.randomUUID(), sponsorNumber: finalSponsor },
      ]);
    }
    this.dialogOpen = false;
  }

  private validate(): string {
    if (!this.form.memberName.trim()) return 'Member Name is required.';
    if (!this.form.identityNumber.trim()) return 'Identity Number is required.';
    if (!this.form.dateOfBirth) return 'Date of Birth is required.';
    if (this.form.memberType === 'Dependent' && !this.form.employeeId) return 'Please select the Employee for this dependent.';
    return '';
  }

  goNext(): void {
    if (this.members.length > 0) this.next.emit();
  }

  downloadTemplate(): void {
    // In real app, use xlsx library
    alert('Template download — integrate xlsx library for production');
  }

  onExcelUpload(event: Event): void {
    // In real app, parse using xlsx library
    alert('Excel upload — integrate xlsx library for production');
  }
}

// src/components/quotation/MembersStep.tsx
import { useState, useCallback, useMemo } from "react";
import { Plus, Upload, Pencil, Trash2, Download } from "lucide-react";
import * as XLSX from "xlsx";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import type { Member, MemberType, ClassSelection, MaritalStatus, Gender } from "@/types/quotation";

const CLASS_OPTIONS: ClassSelection[] = ["VIP", "A", "B", "C", "LM"];

const emptyMember = (sponsorNumber: string): Omit<Member, "id"> => ({
  memberType: "Employee",
  memberName: "",
  identityNumber: "",
  dateOfBirth: "",
  gender: "Male",
  maritalStatus: "Single",
  classSelection: "B",
  sponsorNumber,
});

interface MembersStepProps {
  members: Member[];
  sponsorNumber: string;
  onChange: (members: Member[]) => void;
  onNext: () => void;
  onBack: () => void;
}

const MembersStep = ({ members, sponsorNumber, onChange, onNext, onBack }: MembersStepProps) => {
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<Omit<Member, "id">>(emptyMember(sponsorNumber));
  const [formError, setFormError] = useState("");
  const [uploadErrors, setUploadErrors] = useState<string[]>([]);

  const employees = useMemo(() => members.filter((m) => m.memberType === "Employee"), [members]);

  const openAdd = () => {
    setForm(emptyMember(sponsorNumber));
    setEditingId(null);
    setFormError("");
    setDialogOpen(true);
  };

  const openEdit = (member: Member) => {
    const { id, ...rest } = member;
    setForm(rest);
    setEditingId(id);
    setFormError("");
    setDialogOpen(true);
  };

  const handleDelete = (id: string) => {
    // Also remove dependents of this employee
    const member = members.find((m) => m.id === id);
    if (member?.memberType === "Employee") {
      onChange(members.filter((m) => m.id !== id && m.employeeId !== id));
    } else {
      onChange(members.filter((m) => m.id !== id));
    }
  };

  const validate = (): string => {
    if (!form.memberName.trim()) return "Member Name is required.";
    if (!form.identityNumber.trim()) return "Identity Number is required.";
    if (!form.dateOfBirth) return "Date of Birth is required.";
    if (form.memberType === "Dependent" && !form.employeeId) return "Please select the Employee for this dependent.";
    return "";
  };

  const handleSave = () => {
    const err = validate();
    if (err) { setFormError(err); return; }

    const finalSponsor = form.memberType === "Employee"
      ? sponsorNumber
      : members.find((m) => m.id === form.employeeId)?.identityNumber || sponsorNumber;

    if (editingId) {
      onChange(members.map((m) => m.id === editingId ? { ...form, id: editingId, sponsorNumber: finalSponsor } : m));
    } else {
      onChange([...members, { ...form, id: crypto.randomUUID(), sponsorNumber: finalSponsor }]);
    }
    setDialogOpen(false);
  };

  const handleExcelUpload = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setUploadErrors([]);

    const reader = new FileReader();
    reader.onload = (evt) => {
      try {
        const wb = XLSX.read(evt.target?.result, { type: "array" });
        const ws = wb.Sheets[wb.SheetNames[0]];
        const rows = XLSX.utils.sheet_to_json<Record<string, string>>(ws);
        const errors: string[] = [];
        const newMembers: Member[] = [];

        rows.forEach((row, i) => {
          const rowNum = i + 2;
          const type = (row["MemberType"] || "").trim() as MemberType;
          if (type !== "Employee" && type !== "Dependent") {
            errors.push(`Row ${rowNum}: Invalid MemberType "${type}".`);
            return;
          }
          const name = (row["MemberName"] || "").trim();
          const identity = (row["IdentityNumber"] || "").trim();
          const dob = (row["DateOfBirth"] || "").trim();
          if (!name || !identity || !dob) {
            errors.push(`Row ${rowNum}: Missing required fields.`);
            return;
          }
          const gender = (row["Gender"] as Gender) || "Male";
          const marital = (row["MaritalStatus"] as MaritalStatus) || "Single";
          const cls = (row["Class"] as ClassSelection) || "B";
          const empSponsor = (row["SponsorNumber"] || "").trim();

          if (type === "Dependent") {
            if (!empSponsor) {
              errors.push(`Row ${rowNum}: SponsorNumber is required for Dependents.`);
              return;
            }
            // Check existing + newly added employees
            const allEmps = [...members, ...newMembers].filter((m) => m.memberType === "Employee");
            const matchEmp = allEmps.find((e) => e.identityNumber === empSponsor);
            if (!matchEmp) {
              errors.push(`Row ${rowNum}: No matching Employee with ID "${empSponsor}".`);
              return;
            }
          }

          newMembers.push({
            id: crypto.randomUUID(),
            memberType: type,
            memberName: name,
            identityNumber: identity,
            dateOfBirth: dob,
            gender,
            maritalStatus: marital,
            classSelection: CLASS_OPTIONS.includes(cls) ? cls : "B",
            sponsorNumber: type === "Employee" ? sponsorNumber : empSponsor,
            employeeId: type === "Dependent"
              ? [...members, ...newMembers].find((m) => m.memberType === "Employee" && m.identityNumber === empSponsor)?.id
              : undefined,
          });
        });

        if (errors.length) setUploadErrors(errors);
        if (newMembers.length) onChange([...members, ...newMembers]);
      } catch {
        setUploadErrors(["Failed to parse Excel file."]);
      }
    };
    reader.readAsArrayBuffer(file);
    e.target.value = "";
  }, [members, sponsorNumber, onChange]);

  const handleDownloadTemplate = () => {
    const templateData = [
      { MemberType: "Employee", MemberName: "John Smith", IdentityNumber: "1234567890", DateOfBirth: "1990-01-15", Gender: "Male", MaritalStatus: "Married", Class: "A", SponsorNumber: "" },
      { MemberType: "Dependent", MemberName: "Jane Smith", IdentityNumber: "9876543210", DateOfBirth: "1992-05-20", Gender: "Female", MaritalStatus: "Married", Class: "A", SponsorNumber: "1234567890" },
    ];
    const ws = XLSX.utils.json_to_sheet(templateData);
    ws["!cols"] = [{ wch: 12 }, { wch: 18 }, { wch: 16 }, { wch: 14 }, { wch: 8 }, { wch: 14 }, { wch: 6 }, { wch: 16 }];
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Members");
    XLSX.writeFile(wb, "member_upload_template.xlsx");
  };

  return (
    <div className="space-y-6">
      <Card className="border-border">
        <CardHeader className="pb-4">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
            <CardTitle className="font-heading text-xl">Members</CardTitle>
            <div className="flex flex-wrap gap-2">
              <Button variant="ghost" size="sm" onClick={handleDownloadTemplate}>
                <Download className="mr-1.5 h-4 w-4" /> <span className="hidden xs:inline">Template</span>
              </Button>
              <label htmlFor="excel-upload">
                <Button variant="outline" size="sm" asChild>
                  <span className="cursor-pointer"><Upload className="mr-1.5 h-4 w-4" /> Upload</span>
                </Button>
              </label>
              <input id="excel-upload" type="file" accept=".xlsx,.xls" className="hidden" onChange={handleExcelUpload} />
              <Button size="sm" onClick={openAdd}>
                <Plus className="mr-1.5 h-4 w-4" /> Add
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {uploadErrors.length > 0 && (
            <div className="mb-4 rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive space-y-1">
              <p className="font-semibold">Upload Errors:</p>
              {uploadErrors.map((err, i) => <p key={i}>• {err}</p>)}
            </div>
          )}
          {members.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              <p className="text-sm">No members added yet. Click "Add Member" or upload an Excel file.</p>
              <p className="text-xs mt-2">Excel columns: MemberType, MemberName, IdentityNumber, DateOfBirth, Gender, MaritalStatus, Class, SponsorNumber</p>
            </div>
          ) : (
            <div className="overflow-auto max-h-[420px]">
              <table className="w-full text-sm">
                <thead className="sticky top-0 bg-card z-10">
                  <tr className="border-b border-border text-left">
                    <th className="py-2.5 px-3 font-semibold text-muted-foreground">Name</th>
                    <th className="py-2.5 px-3 font-semibold text-muted-foreground">Type</th>
                    <th className="py-2.5 px-3 font-semibold text-muted-foreground hidden sm:table-cell">Sponsor #</th>
                    <th className="py-2.5 px-3 font-semibold text-muted-foreground">Class</th>
                    <th className="py-2.5 px-3 font-semibold text-muted-foreground hidden md:table-cell">Marital</th>
                    <th className="py-2.5 px-3 font-semibold text-muted-foreground text-right">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {members.map((m) => (
                    <tr key={m.id} className="border-b border-border last:border-0 hover:bg-muted/50 transition-colors">
                      <td className="py-2.5 px-3 font-medium text-foreground">{m.memberName}</td>
                      <td className="py-2.5 px-3">
                        <Badge variant="outline" className={m.memberType === "Employee" ? "border-primary/30 text-primary" : ""}>{m.memberType}</Badge>
                      </td>
                      <td className="py-2.5 px-3 text-muted-foreground hidden sm:table-cell">{m.sponsorNumber}</td>
                      <td className="py-2.5 px-3"><Badge variant="secondary">{m.classSelection}</Badge></td>
                      <td className="py-2.5 px-3 text-muted-foreground hidden md:table-cell">{m.maritalStatus}</td>
                      <td className="py-2.5 px-3 text-right">
                        <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => openEdit(m)}>
                          <Pencil className="h-3.5 w-3.5" />
                        </Button>
                        <Button variant="ghost" size="icon" className="h-8 w-8 text-destructive" onClick={() => handleDelete(m.id)}>
                          <Trash2 className="h-3.5 w-3.5" />
                        </Button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
          <p className="text-xs text-muted-foreground mt-3">{members.length} member(s) added</p>
        </CardContent>
      </Card>

      <div className="hidden sm:flex justify-between">
        <Button variant="outline" onClick={onBack}>Back</Button>
        <Button onClick={() => { if (members.length === 0) return; onNext(); }} disabled={members.length === 0}>Continue</Button>
      </div>

      {/* Sticky mobile bottom bar */}
      <div className="fixed bottom-0 left-0 right-0 z-40 border-t border-border bg-card/95 backdrop-blur-md p-3 flex gap-3 sm:hidden">
        <Button variant="outline" onClick={onBack} className="flex-1">Back</Button>
        <Button onClick={() => { if (members.length === 0) return; onNext(); }} disabled={members.length === 0} className="flex-1">Continue</Button>
      </div>

      {/* Add/Edit Dialog */}
      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="font-heading">{editingId ? "Edit" : "Add"} Member</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div className="space-y-1.5">
              <Label>Member Type</Label>
              <Select value={form.memberType} onValueChange={(v) => setForm({ ...form, memberType: v as MemberType, employeeId: undefined })}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="Employee">Employee</SelectItem>
                  <SelectItem value="Dependent">Dependent</SelectItem>
                </SelectContent>
              </Select>
            </div>
            {form.memberType === "Dependent" && (
              <div className="space-y-1.5">
                <Label>Select Employee *</Label>
                <Select value={form.employeeId || ""} onValueChange={(v) => setForm({ ...form, employeeId: v })}>
                  <SelectTrigger><SelectValue placeholder="Choose employee" /></SelectTrigger>
                  <SelectContent>
                    {employees.map((emp) => (
                      <SelectItem key={emp.id} value={emp.id}>{emp.memberName} ({emp.identityNumber})</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {employees.length === 0 && <p className="text-xs text-destructive">Add an employee first.</p>}
              </div>
            )}
            <div className="space-y-1.5">
              <Label>Member Name *</Label>
              <Input value={form.memberName} onChange={(e) => setForm({ ...form, memberName: e.target.value })} />
            </div>
            <div className="space-y-1.5">
              <Label>Identity Number *</Label>
              <Input value={form.identityNumber} onChange={(e) => setForm({ ...form, identityNumber: e.target.value })} />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label>Date of Birth *</Label>
                <Input type="date" value={form.dateOfBirth} onChange={(e) => setForm({ ...form, dateOfBirth: e.target.value })} />
              </div>
              <div className="space-y-1.5">
                <Label>Gender</Label>
                <Select value={form.gender} onValueChange={(v) => setForm({ ...form, gender: v as Gender })}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Male">Male</SelectItem>
                    <SelectItem value="Female">Female</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label>Marital Status</Label>
                <Select value={form.maritalStatus} onValueChange={(v) => setForm({ ...form, maritalStatus: v as MaritalStatus })}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Single">Single</SelectItem>
                    <SelectItem value="Married">Married</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1.5">
                <Label>Class *</Label>
                <Select value={form.classSelection} onValueChange={(v) => setForm({ ...form, classSelection: v as ClassSelection })}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {CLASS_OPTIONS.map((c) => <SelectItem key={c} value={c}>{c}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
            </div>
            {formError && <p className="text-sm text-destructive">{formError}</p>}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialogOpen(false)}>Cancel</Button>
            <Button onClick={handleSave}>{editingId ? "Update" : "Add"}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default MembersStep;
