// public/angular-project/src/app/shared/components/step-indicator/step-indicator.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-step-indicator',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="flex items-center justify-center gap-2 mb-8">
      @for (step of steps; track step.index; let i = $index) {
        <div class="flex items-center gap-2">
          <div class="flex items-center justify-center w-8 h-8 rounded-full text-xs font-bold transition-colors"
               [class.bg-primary]="i <= currentStep"
               [class.text-primary-foreground]="i <= currentStep"
               [class.bg-muted]="i > currentStep"
               [class.text-muted-foreground]="i > currentStep">
            {{ i + 1 }}
          </div>
          <span class="text-xs font-medium hidden sm:inline"
                [class.text-foreground]="i <= currentStep"
                [class.text-muted-foreground]="i > currentStep">
            {{ step.label }}
          </span>
          @if (i < steps.length - 1) {
            <div class="w-8 h-0.5 transition-colors"
                 [class.bg-primary]="i < currentStep"
                 [class.bg-border]="i >= currentStep">
            </div>
          }
        </div>
      }
    </div>
  `,
})
export class StepIndicatorComponent {
  @Input() currentStep = 0;

  steps = [
    { index: 0, label: 'Sponsor' },
    { index: 1, label: 'Members' },
    { index: 2, label: 'Health' },
    { index: 3, label: 'Quotation' },
    { index: 4, label: 'KYC' },
    { index: 5, label: 'Payment' },
  ];
}

// src/components/quotation/StepIndicator.tsx
import { Check } from "lucide-react";
import { cn } from "@/lib/utils";

const steps = ["Sponsor", "Members", "Health Declaration", "Quotation", "KYC", "Payment"];

interface StepIndicatorProps {
  currentStep: number;
}

const StepIndicator = ({ currentStep }: StepIndicatorProps) => {
  return (
    <div className="flex items-center justify-center gap-0 mb-8">
      {steps.map((label, i) => {
        const isCompleted = i < currentStep;
        const isCurrent = i === currentStep;
        return (
          <div key={label} className="flex items-center">
            <div className="flex flex-col items-center gap-1.5">
              <div
                className={cn(
                  "flex h-9 w-9 items-center justify-center rounded-full text-sm font-bold transition-colors",
                  isCompleted && "bg-primary text-primary-foreground",
                  isCurrent && "bg-primary text-primary-foreground ring-4 ring-primary/20",
                  !isCompleted && !isCurrent && "bg-muted text-muted-foreground"
                )}
              >
                {isCompleted ? <Check className="h-4 w-4" /> : i + 1}
              </div>
              <span
                className={cn(
                  "text-xs font-medium whitespace-nowrap",
                  isCurrent ? "text-primary" : isCompleted ? "text-foreground" : "text-muted-foreground"
                )}
              >
                {label}
              </span>
            </div>
            {i < steps.length - 1 && (
              <div
                className={cn(
                  "h-0.5 w-10 sm:w-16 md:w-24 mx-2 mt-[-1.25rem]",
                  i < currentStep ? "bg-primary" : "bg-border"
                )}
              />
            )}
          </div>
        );
      })}
    </div>
  );
};

export default StepIndicator;
